### ISSUE TITLE
Huge Library size 

### ISSUE THREAD

**Issue by pharidali** [khalti/khalti-android#16]
Hey Developer,

You should decrease the library size at first. And You should use latest version of Picasso. 

Regards

**Comment by ishowrunes** [comment]
Version 1.02.09 uses the latest picasso version. Please update your dependency. We are working on reducing the library size.

**Comment by pharidali** [comment]
Okay, Thanks for the Nice Sdk. We have integrated to our App MSecurity.

https://play.google.com/store/apps/details?id=com.phariddot.pasecurity

**Comment by ishowrunes** [comment]
Please use the version 2 of the library. If you have any problem please open a new issue
