### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by MhrznSomanjali** [khalti/khalti-android#18]
java.lang.NoSuchFieldError: No static field flProgress of type I in class Lcom/khalti/R$id; or its superclasses (declaration of 'com.khalti.R$id' appears in /data/app/com.app.vianet-25MVUnyLsz_YpBijZYnvQA==/base.apk!classes2.dex)

**Comment by ishowrunes** [comment]
I think this because of duplicate resource id. Check if you also have a `flProgress`

**Comment by sarbagyastha** [comment]
Reopen if needed.
