### ISSUE TITLE
ignored khalti-android/src/main/java/khalti/utils/Constant.java

### ISSUE THREAD

**Issue by niroj08** [khalti/khalti-android#2]
Whats the meaning of making the project open source when I can't even test your testClasses.

 khalti-android/src/main/java/khalti/checkOut/EBanking/EBankingPresenter.java
 khalti-android/src/main/java/khalti/checkOut/Wallet/WalletPresenter.java
 khalti-android/src/main/java/khalti/checkOut/api/ApiHelper.java

Constants.url is missing and which is for sure "https://khalti.com/" as I assume..

Looking for better sdk ahead
Congratulation as well !!

**Comment by ishowrunes** [comment]
I removed Constants from gitignore. So, it should work now.
