### ISSUE TITLE
Could not resolve com.khalti:khalti-android:1.02.18.

### ISSUE THREAD

**Issue by pranishres** [khalti/khalti-android#20]
I was using version `1.02.18` khalti sdk version. Now when I tried rebuild my `android project` I am getting this error. Has this version been removed from khalti repo or is it some issue in my side? Please explain.

`RROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.khalti:khalti-android:1.02.18.`

**Comment by abnormalbbk** [comment]
![khalti sdk release history](https://user-images.githubusercontent.com/5323624/77501663-c187e780-6e80-11ea-9a58-fcec2d484181.png)
Released versions.
Didn't find any version related to 1.02.18. 
Also it would be great if you migrate to the latest version 😃

**Comment by pranishres** [comment]
Yes bro I am saying the same thing. I didnot find the version 1.02.18 of khalti which I had been using for few months. And yes I can update to the lates version but I did not find the proper change log document (from 1.02.18 to 2.00.00) in your repository which I need for QA.
<img width="1036" alt="changelog" src="https://user-images.githubusercontent.com/6890014/77505711-049b8800-6e8c-11ea-80c7-28a94aab2940.png">

**Comment by ishowrunes** [comment]
@pranishres I do not follow your issue. What is the issue in changelog?

**Comment by sarbagyastha** [comment]
Please re-open the issue if needed.
