### ISSUE TITLE
[Feature Request] onCancelled callback

### ISSUE THREAD

**Issue by awazgyawali** [khalti/khalti-android#23]
The industry-standard approach to add a 3rd party system which need some redirect is to have 3 callbacks, success, failed, cancelled. But this SDK lacks cancelled, without the ability to know whethere the sdk tried to make the payment, we are not able to optimize out sales accordingly.

Will it be a possibility from the team to add such a feature?

**Comment by ishowrunes** [comment]
Noted. Currently working on a new update

**Comment by sarbagyastha** [comment]
Closing as this was added in `v2.01.00`
