### ISSUE TITLE
Cannot find symbol Khalti.init when called from Java.

### ISSUE THREAD

**Issue by therealyubraj** [khalti/khalti-android#37]
When trying to call the `init` method of Khalti, I get `cannot find symbol` error.
```java
         KhaltiPayConfig config = new KhaltiPayConfig(
                "public_key",
                "pidx_from_epayment_initiate",
                true,
                Environment.TEST
        );
        Khalti.init(ctx, config,
                // on payment result
                (paymentResult, khalti) -> {
                    Log.d("khalti", "On payment result");
                },
                // on message
                (payload, khalti) -> {
                    Log.d("khalti", "On message");
                },
                // on return
                (khalti) -> {
                    Log.d("khalti", "On return");
                }
        );
```

Reading the Kotlin doc for calling Kotlin static methods from java, `@JvmStatic` is required.
Link to the [doc.](https://kotlinlang.org/docs/java-to-kotlin-interop.html#static-methods)

**Comment by ishowrunes** [comment]
Can you post the stacktrace and please provide a minimum reproducible code

**Comment by ishowrunes** [comment]
How are you trying to invoke the `init` function? I can successfully invoke the function as follows:

``` java
Khalti.companion.init(...);
```

**Comment by therealyubraj** [comment]
I see. It seems the `Khalti.Companion.init(...)` does work. My bad, thanks a lot. @Ishwor-Shrestha
