### ISSUE TITLE
App remove from play store due to SMS permission declared in Manifest.

### ISSUE THREAD

**Issue by subashz** [khalti/khalti-android#9]
Can you please make SMS permission optional on the SDK. Since, SMS permission on SDK is mainly required for the auto read of the SMS? More detail her:  https://support.google.com/googleplay/android-developer/answer/9047303

**Comment by txudeep** [comment]
I have also got similar issue and my app got rejected from playstore. Please fix this issue as soon as possible.

**Comment by abnormalbbk** [comment]
Sms permission has been removed in the latest version so please update the sdk to latest.

**Comment by subashz** [comment]
SMS permission has been removed only in the develop branch, no merge in the master. please merge the branch and release..
